name: Build Base
on: workflow_dispatch
jobs:
  build-arm64:
    name: Build ARM64
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:qemu-v5.2.0
          platforms: arm64

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: |
          make base-arm64-ovs
          
      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker images
          docker tag kube-ovn/ovs-base:base-ovs-arm64 zhaiyj2/ovs-base:base-ovs-arm
          docker push zhaiyj2/ovs-base:base-ovs-arm
          
     
 
